import {
  mkdir,
  writeFile
} from "node:fs/promises";

import {
  join
} from "node:path";

import {
  definePackage,
  type OEAPAppManifest
} from "@oeap/package-spec";

import type {
  AppBlueprint
} from "@oeap/app-builder";

export interface BuildAppPackageOptions {
  blueprint: AppBlueprint;
  packageId: string;
  publisher: string;
  version?: string;
  outputDir: string;
  directoryName?: string;
}

export interface BuiltAppPackage {
  directory: string;
  manifest: OEAPAppManifest;
}

function slugify(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fff]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export class AppPackageBuilder {
  async build(
    options: BuildAppPackageOptions
  ): Promise<BuiltAppPackage> {
    const version =
      options.version ?? "0.0.1";

    const appSlug =
      slugify(options.blueprint.appName) ||
      "generated-app";

    const directoryName =
      options.directoryName?.trim() ||
      appSlug;

    const directory =
      join(
        options.outputDir,
        directoryName
      );

    await mkdir(
      directory,
      {
        recursive: true
      }
    );

    const recommended =
      options.blueprint.recommendedPackages;

    const dependencyPackages = [
      ...recommended.skills,
      ...recommended.agents,
      ...recommended.connectors
    ];

    const manifest = definePackage({
      schemaVersion: "1.0",
      id: options.packageId,
      type: "app",
      name: appSlug,
      displayName:
        options.blueprint.appName,
      description:
        options.blueprint.summary,
      version,
      publisher:
        options.publisher,

      packages:
        dependencyPackages,

      navigation:
        options.blueprint.pages.map(
          (page) => ({
            id: page.id,
            label: page.label,
            path: `/${page.id}`
          })
        ),

      metadata: {
        blueprintVersion: "1.0",

        roles:
          options.blueprint.roles,

        entities:
          options.blueprint.entities,

        workflows:
          options.blueprint.workflows,

        recommendedPackages:
          options.blueprint
            .recommendedPackages
      }
    } satisfies OEAPAppManifest);

    await writeFile(
      join(
        directory,
        "oeap.package.json"
      ),
      JSON.stringify(
        manifest,
        null,
        2
      ),
      "utf8"
    );

    await writeFile(
      join(
        directory,
        "app.blueprint.json"
      ),
      JSON.stringify(
        options.blueprint,
        null,
        2
      ),
      "utf8"
    );

    await writeFile(
      join(
        directory,
        "package.json"
      ),
      JSON.stringify(
        {
          name:
            `@${options.publisher}/${appSlug}`,
          version,
          private: false,
          type: "module",
          oeap: {
            manifest:
              "./oeap.package.json"
          }
        },
        null,
        2
      ),
      "utf8"
    );

    const readme = `# ${options.blueprint.appName}

${options.blueprint.summary}

Generated by Open Enterprise AI Platform.

## Roles

${options.blueprint.roles
  .map((role) => `- ${role.name}`)
  .join("\n")}

## Pages

${options.blueprint.pages
  .map((page) => `- ${page.label}`)
  .join("\n")}

## Package ID

${options.packageId}
`;

    await writeFile(
      join(
        directory,
        "README.md"
      ),
      readme,
      "utf8"
    );

    return {
      directory,
      manifest
    };
  }
}

export const appPackageBuilder =
  new AppPackageBuilder();
